@extends('layouts.page')

@section('title', 'Audience Estimate Sources')

@section('css')
<style>
.source-hero{background:#08172c;color:#fff;border-radius:20px;padding:26px 28px}.source-card{border:1px solid #e7edf5;border-radius:16px;background:#fff;padding:18px;height:100%}.source-card h5{color:#10233f;font-weight:900}.source-status{font-size:11px;font-weight:800;border-radius:999px;padding:5px 9px;background:#edf2f7;color:#5e7189}.source-note{font-size:12px;color:#718096;line-height:1.6}.vault-note{border-left:4px solid #00a8e8;background:#effaff;padding:14px 16px;color:#17486a;border-radius:0 12px 12px 0}.account-table td,.account-table th{vertical-align:middle}.account-table{font-size:13px}.credential-field{position:relative}.credential-field .toggle-password{position:absolute;right:8px;top:33px;border:0;background:transparent;color:#698098}
</style>
@endsection

@section('content')
<div class="subheader"><h1 class="subheader-title"><i class="subheader-icon fal fa-link"></i> Audience Estimate <span class="fw-300">Source Accounts</span><small>Hubungkan sumber berizin untuk collector read-only lintas jaringan bioskop.</small></h1></div>
<div class="source-hero mb-4"><div class="text-uppercase small font-weight-bold" style="letter-spacing:.14em;color:#9fe8ff">Multi-chain collector registry</div><h2 class="mb-2 mt-2">Satu ranking nasional, banyak source yang dapat dipertanggungjawabkan.</h2><p class="mb-0 text-white-50">Tambahkan source untuk XXI, CGV, Cinépolis, atau jaringan lain. Akun hanya untuk akses yang Mumu miliki atau izinkan; collector tidak boleh booking, hold kursi, checkout, maupun bypass CAPTCHA.</p></div>
<div class="vault-note mb-4"><strong>Credential Vault:</strong> username, password, dan token disimpan terenkripsi pada server. Setelah tersimpan, rahasia tidak pernah dikirim kembali ke browser atau ditampilkan di daftar akun.</div>
<div class="row">
 <div class="col-lg-5 mb-4"><div class="source-card"><h5>Tambah Source</h5><p class="source-note">Source adalah provider/jaringan, bukan satu bioskop. Satu source boleh punya beberapa akun atau connector.</p><form id="source-form"><div class="form-group"><label>Provider</label><select class="form-control" name="provider" required><option value="cinepolis">Cinépolis</option><option value="cgv">CGV</option><option value="xxi">Cinema XXI / m.tix</option><option value="other">Jaringan lain</option></select></div><div class="form-group"><label>Label</label><input class="form-control" name="label" placeholder="Contoh: Cinema XXI public booking" required></div><div class="form-group"><label>Base URL <span class="text-muted">(opsional)</span></label><input type="url" class="form-control" name="base_url" placeholder="https://..."></div><div class="form-group"><label>Catatan <span class="text-muted">(opsional)</span></label><textarea class="form-control" name="notes" rows="3" placeholder="Cakupan, izin, atau ketentuan source."></textarea></div><button class="btn btn-primary" type="submit"><i class="fal fa-plus mr-1"></i> Simpan Source</button></form></div></div>
 <div class="col-lg-7 mb-4"><div class="source-card"><h5>Tambah Akun Berizin</h5><p class="source-note">Gunakan hanya credential yang memang berhak Mumu gunakan. Bisa username/password atau token resmi. Akun dapat dihapus, tetapi credential tidak pernah dapat dibaca kembali.</p><form id="account-form"><div class="row"><div class="col-md-6 form-group"><label>Source</label><select class="form-control" name="source_uuid" required><option value="">Pilih source</option>@foreach($sources as $source)<option value="{{ $source->uuid }}">{{ strtoupper($source->provider) }} — {{ $source->label }}</option>@endforeach</select></div><div class="col-md-6 form-group"><label>Label Akun</label><input class="form-control" name="label" placeholder="Contoh: Akun monitoring legal" required></div></div><div class="row"><div class="col-md-6 form-group credential-field"><label>Username / Email</label><input class="form-control" name="username" autocomplete="off"></div><div class="col-md-6 form-group credential-field"><label>Password</label><input class="form-control" name="password" type="password" autocomplete="new-password"><button class="toggle-password" type="button" data-target="password" aria-label="Tampilkan password"><i class="fal fa-eye"></i></button></div></div><div class="form-group credential-field"><label>Access Token <span class="text-muted">(gunakan sebagai alternatif credential)</span></label><input class="form-control" name="access_token" type="password" autocomplete="off"><button class="toggle-password" type="button" data-target="access_token" aria-label="Tampilkan token"><i class="fal fa-eye"></i></button></div><div class="custom-control custom-checkbox mb-3"><input type="checkbox" class="custom-control-input" id="authorization_confirmed" name="authorization_confirmed" value="1" required><label class="custom-control-label" for="authorization_confirmed">Saya mengonfirmasi akun/API ini milik saya atau saya berwenang menggunakannya untuk monitoring read-only.</label></div><button class="btn btn-success" type="submit"><i class="fal fa-lock mr-1"></i> Simpan Terenkripsi</button></form></div></div>
</div>
<div class="source-card"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-1">Source Registry</h5><p class="source-note mb-0">Status koneksi baru akan berubah setelah collector adapter benar-benar diverifikasi.</p></div><a class="btn btn-outline-primary" href="{{ route('seatmap-monitor.index') }}"><i class="fal fa-chart-line mr-1"></i> Lihat Ranking</a></div><div class="table-responsive"><table class="table account-table mb-0"><thead><tr><th>Provider</th><th>Label</th><th>Base URL</th><th>Accounts</th><th>Status</th></tr></thead><tbody>@forelse($sources as $source)<tr><td><strong>{{ strtoupper($source->provider) }}</strong></td><td>{{ $source->label }}</td><td class="text-muted">{{ $source->base_url ?: '—' }}</td><td>{{ $source->accounts_count }}</td><td><span class="source-status">{{ strtoupper($source->status) }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada source. Tambahkan jaringan bioskop pertama di atas.</td></tr>@endforelse</tbody></table></div></div>
@endsection

@section('js')
<script src="{{ asset('js/notifications/sweetalert2/sweetalert2.bundle.js') }}"></script>
<script>
(function(){
 const csrf=document.querySelector('meta[name="csrf-token"]').content;
 const sourceUrl=@json(route('seatmap-monitor.sources.store'));
 const accountUrl=@json(route('seatmap-monitor.accounts.store'));
 function firstError(payload){if(payload && payload.errors){const key=Object.keys(payload.errors)[0];return payload.errors[key][0];}return (payload&&payload.message)||'Permintaan gagal diproses.';}
 function submit(form,url){const button=form.querySelector('button[type="submit"]');button.disabled=true;fetch(url,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json','X-Requested-With':'XMLHttpRequest'},body:new FormData(form)}).then(async r=>{const p=await r.json();if(!r.ok)throw p;return p;}).then(p=>Swal.fire({icon:'success',title:'Tersimpan',text:p.message}).then(()=>window.location.reload())).catch(p=>Swal.fire({icon:'error',title:'Tidak dapat disimpan',text:firstError(p)})).finally(()=>button.disabled=false);}
 document.getElementById('source-form').addEventListener('submit',e=>{e.preventDefault();submit(e.currentTarget,sourceUrl);});
 document.getElementById('account-form').addEventListener('submit',e=>{e.preventDefault();submit(e.currentTarget,accountUrl);});
 document.querySelectorAll('.toggle-password').forEach(btn=>btn.addEventListener('click',()=>{const input=btn.closest('.credential-field').querySelector('input');const show=input.type==='password';input.type=show?'text':'password';btn.querySelector('i').className=show?'fal fa-eye-slash':'fal fa-eye';btn.setAttribute('aria-label',show?'Sembunyikan rahasia':'Tampilkan rahasia');}));
})();
</script>
@endsection
