@extends('layouts.page')

@section('title', 'Tambah Bioskop')

@section('css')
<link rel="stylesheet" media="screen, print" href="{{ asset('css/formplugins/select2/select2.bundle.css') }}">
<style>
.cinema-wizard{max-width:1080px;margin:0 auto}.cinema-wizard>.panel{height:780px;display:flex;flex-direction:column}.cinema-wizard>.panel>.panel-container{height:calc(100% - 54px);min-height:0;overflow:hidden}.cinema-wizard>.panel>.panel-container>.panel-content{height:100%;display:flex;flex-direction:column}.wizard-steps{display:flex;overflow:auto;border-bottom:1px solid #e5e9f2;margin-bottom:24px;flex:0 0 auto;min-height:64px;align-items:stretch}.wizard-step{flex:1;min-width:170px;display:flex;align-items:center;gap:10px;padding:14px 15px;border:0;border-bottom:3px solid transparent;background:transparent;color:#7d8797;text-align:left;font-weight:600}.step-no{width:30px;height:30px;flex:0 0 30px;border-radius:50%;display:grid;place-items:center;background:#eef1f6;color:#687385;font-size:12px}.wizard-step.active{color:#2769c8;border-bottom-color:#2769c8}.wizard-step.active .step-no{background:#2769c8;color:#fff}.wizard-step.done .step-no{background:#18a06e;color:#fff}.step-copy small{display:block;font-weight:400;color:#97a0ad}.wizard-pane-stage{height:560px;overflow-y:auto;overflow-x:hidden;scrollbar-gutter:stable}.wizard-pane{display:none}.wizard-pane.active{display:block;animation:wizardIn .18s ease}.wizard-note{border-left:3px solid #4f8fe8;background:#f4f8ff;padding:14px 16px;color:#41536d;margin-bottom:22px}.price-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.price-card{border:1px solid #e3e8f0;border-top:3px solid #2769c8;padding:16px;background:#fff}.price-card label{font-weight:600;font-size:12px}.repeat-card{border:1px solid #e3e8f0;border-left:4px solid #4f8fe8;padding:16px;margin-bottom:12px;background:#fff}.capacity-card{border-left-color:#18a06e}.row-label{font-size:11px;font-weight:700;color:#8490a1;letter-spacing:.08em;text-transform:uppercase}.empty-repeat{border:1px dashed #b7c3d4;padding:23px;text-align:center;color:#718096;background:#fbfcfe}.wizard-footer{margin-top:28px;padding-top:20px;border-top:1px solid #e8ecf2;display:flex;justify-content:space-between;gap:12px}@keyframes wizardIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}@media(max-width:650px){.wizard-step{min-width:150px}.step-copy small{display:none}.price-grid{grid-template-columns:1fr}}
</style>
@endsection

@section('content')
@php($categoryNames = $bioskop_kategori->toArray())
<div class="col-xxl cinema-wizard"><div class="panel"><div class="panel-hdr"><h2>Tambah Baru <span class="fw-300"><i>Bioskop</i></span></h2><div class="panel-toolbar"><a class="nav-link active" href="{{ route('masterbioskop.index') }}"><i class="fal fa-arrow-alt-left"></i> Kembali</a></div></div><div class="panel-container show"><div class="panel-content">
@if($errors->any())<div class="alert alert-danger"><strong>Data belum dapat disimpan.</strong><ul class="mb-0 mt-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="wizard-steps" role="tablist">
<button type="button" class="wizard-step active" data-step="0"><span class="step-no">1</span><span class="step-copy">Bioskop<small>Identitas dan lokasi</small></span></button>
<button type="button" class="wizard-step" data-step="1"><span class="step-no">2</span><span class="step-copy">Tipe tiket<small>Master kategori</small></span></button>
<button type="button" class="wizard-step" data-step="2"><span class="step-no">3</span><span class="step-copy">Kapasitas<small>Studio dan kursi</small></span></button>
<button type="button" class="wizard-step d-none" data-step="3" data-price-step><span class="step-no">4</span><span class="step-copy">Harga REGULAR<small>Khusus XXI</small></span></button>
</div>
{!! Form::open(['route'=>'masterbioskop.store','method'=>'POST','id'=>'cinema-wizard-form']) !!}
<div class="wizard-pane-stage">
<div class="wizard-pane active" data-pane="0"><div class="wizard-note"><strong>Mulai dari bioskop.</strong> Master pendukung yang ditambahkan di langkah berikutnya akan terhubung otomatis.</div><div class="row"><div class="form-group col-md-6"><label class="required form-label">Kategori Bioskop</label>{!! Form::select('type',$bioskop_kategori,old('type'),['id'=>'type','class'=>'custom-select','required','placeholder'=>'Pilih kategori bioskop...']) !!}</div><div class="form-group col-md-6"><label class="required form-label">Nama Bioskop</label><input name="nama_bioskop" value="{{ old('nama_bioskop') }}" class="form-control" required></div><div class="form-group col-md-4"><label class="required form-label">Kota</label><input name="kota" value="{{ old('kota') }}" class="form-control" required></div><div class="form-group col-md-4"><label class="form-label">Pajak (%)</label><input name="pajak" value="{{ old('pajak') }}" type="number" min="0" max="100" step="0.01" class="form-control"></div><div class="form-group col-md-4"><label class="form-label">No. Telepon</label><input name="no_telephone" value="{{ old('no_telephone') }}" class="form-control"></div></div></div>
<div class="wizard-pane" data-pane="1"><div class="wizard-note">Tambahkan tipe tiket khusus bila belum tersedia di kategori ini. Langkah ini opsional.</div><div id="ticket-types-list"></div><div id="ticket-types-empty" class="empty-repeat">Belum ada tipe tiket baru.</div><button type="button" id="add-ticket-type" class="btn btn-outline-primary mt-3"><i class="fal fa-plus mr-1"></i>Tambah tipe tiket</button></div>
<div class="wizard-pane" data-pane="2"><div class="wizard-note">Atur kapasitas per studio bila sudah tersedia. Langkah ini opsional.</div><div id="capacity-list"></div><div id="capacity-empty" class="empty-repeat">Belum ada kapasitas.</div><button type="button" id="add-capacity" class="btn btn-outline-success mt-3"><i class="fal fa-plus mr-1"></i>Tambah kapasitas</button></div>
<div class="wizard-pane" data-pane="3" data-price-step><div class="wizard-note"><strong>Harga REGULAR XXI.</strong> Harga ini dipakai oleh import PDF XXI berdasarkan tanggal laporan. Kosongkan seluruh field apabila harga belum siap; import PDF akan tetap diblokir sampai harga diatur.</div><div class="row"><div class="form-group col-md-6"><label class="form-label">Berlaku mulai</label><input name="ticket_price[valid_from]" type="date" value="{{ old('ticket_price.valid_from', now()->startOfMonth()->toDateString()) }}" class="form-control price-input"></div><div class="form-group col-md-6"><label class="form-label">Berlaku sampai</label><input name="ticket_price[valid_until]" type="date" value="{{ old('ticket_price.valid_until') }}" class="form-control price-input"><small class="text-muted">Kosong jika masih berlaku.</small></div></div><div class="price-grid"><div class="price-card"><label>Senin–Kamis</label><input name="ticket_price[weekday_price]" type="text" inputmode="decimal" value="{{ old('ticket_price.weekday_price') }}" class="form-control price-input" placeholder="40.000,00"></div><div class="price-card"><label>Jumat</label><input name="ticket_price[friday_price]" type="text" inputmode="decimal" value="{{ old('ticket_price.friday_price') }}" class="form-control price-input" placeholder="40.000,00"></div><div class="price-card"><label>Sabtu/Minggu & hari libur</label><input name="ticket_price[weekend_holiday_price]" type="text" inputmode="decimal" value="{{ old('ticket_price.weekend_holiday_price') }}" class="form-control price-input" placeholder="40.000,00"></div></div></div>
</div>
<div class="wizard-footer"><button type="button" id="wizard-prev" class="btn btn-outline-secondary d-none"><i class="fal fa-arrow-left mr-1"></i>Kembali</button><span></span><button type="button" id="wizard-next" class="btn btn-primary">Lanjut<i class="fal fa-arrow-right ml-1"></i></button><button type="submit" id="wizard-submit" class="btn btn-success d-none"><i class="fal fa-save mr-1"></i>Simpan semua data</button></div>
{!! Form::close() !!}
</div></div></div></div>
@endsection
@section('js')
<script src="{{ asset('js/formplugins/select2/select2.bundle.js') }}"></script>
<script>
$(function(){
const categoryNames=@json($categoryNames), isXxi=()=>String(categoryNames[$('#type').val()]||'').toUpperCase()==='XXI'; let current=0,ticketIndex=0,capacityIndex=0,categoryTickets={}; $('#type').select2();
const escapeHtml=v=>$('<div>').text(v||'').html(); const ticketOptions=selected=>{let html='<option value="">Pilih tipe tiket...</option>';$.each(categoryTickets,(uuid,name)=>html+='<option value="'+escapeHtml(uuid)+'" '+(String(uuid)===String(selected)?'selected':'')+'>'+escapeHtml(name)+'</option>');$('#ticket-types-list input.ticket-name').each(function(){const i=$(this).data('index'),name=$(this).val().trim();if(name)html+='<option value="new:'+i+'" '+('new:'+i===String(selected)?'selected':'')+'>'+escapeHtml(name)+' (baru)</option>';});return html};
function syncCapacityTickets(){$('#capacity-list select.ticket-select').each(function(){const selected=$(this).val();$(this).html(ticketOptions(selected))});$('#capacity-empty').toggle(!$('#capacity-list .capacity-card').length)} function loadCategoryTickets(){const category=$('#type').val();if(!category){categoryTickets={};syncCapacityTickets();return}$.get("{{ route('ref.type') }}",{kategori:category},data=>{categoryTickets=data||{};syncCapacityTickets()})}
function addTicket(value){const i=ticketIndex++;$('#ticket-types-empty').hide();$('#ticket-types-list').append('<div class="repeat-card ticket-card"><div class="d-flex justify-content-between mb-2"><span class="row-label">Tipe tiket '+(i+1)+'</span><button type="button" class="btn btn-sm btn-outline-danger remove-ticket">Hapus</button></div><input data-index="'+i+'" name="ticket_types['+i+'][name]" value="'+escapeHtml(value)+'" class="form-control ticket-name" placeholder="Contoh: REGULAR"></div>');syncCapacityTickets()}
function addCapacity(row={}){const i=capacityIndex++;$('#capacity-empty').hide();$('#capacity-list').append('<div class="repeat-card capacity-card"><div class="d-flex justify-content-between mb-2"><span class="row-label">Kapasitas '+(i+1)+'</span><button type="button" class="btn btn-sm btn-outline-danger remove-capacity">Hapus</button></div><div class="row"><div class="col-md-4 form-group mb-md-0"><label>Tipe tiket</label><select name="capacities['+i+'][ticket_type_ref]" class="custom-select ticket-select" required>'+ticketOptions(row.ticket_type_ref||'')+'</select></div><div class="col-md-4 form-group mb-md-0"><label>Studio</label><input name="capacities['+i+'][studio]" value="'+escapeHtml(row.studio)+'" class="form-control" required></div><div class="col-md-4 form-group mb-md-0"><label>Kapasitas kursi</label><input name="capacities['+i+'][kapasitas]" value="'+escapeHtml(row.kapasitas)+'" type="number" min="0" class="form-control" required></div></div></div>')}
($('#type').on('change',()=>{loadCategoryTickets();const last=steps()-1;showStep(current>last?last:current)}),$('#add-ticket-type').on('click',()=>addTicket('')),$('#add-capacity').on('click',()=>addCapacity()),$(document).on('input','.ticket-name',syncCapacityTickets).on('click','.remove-ticket',function(){$(this).closest('.ticket-card').remove();syncCapacityTickets()}).on('click','.remove-capacity',function(){$(this).closest('.capacity-card').remove();syncCapacityTickets()}));
function steps(){return isXxi()?4:3}function validate(step){let valid=true;$('[data-pane="'+step+'"]').find('[required]').each(function(){if(!this.checkValidity()){this.reportValidity();valid=false;return false}});return valid}function showStep(step){current=step;$('[data-price-step]').toggleClass('d-none',!isXxi());$('.wizard-pane').removeClass('active');$('[data-pane="'+step+'"]').addClass('active');$('.wizard-step').removeClass('active').each(function(){$(this).toggleClass('done',Number($(this).data('step'))<step)});$('.wizard-step[data-step="'+step+'"]').addClass('active');$('#wizard-prev').toggleClass('d-none',step===0);const last=steps()-1;$('#wizard-next').toggleClass('d-none',step===last);$('#wizard-submit').toggleClass('d-none',step!==last)} $('#wizard-next').on('click',()=>{if(validate(current))showStep(Math.min(steps()-1,current+1))});$('#wizard-prev').on('click',()=>showStep(Math.max(0,current-1)));$('.wizard-step').on('click',function(){const target=Number($(this).data('step'));if(target<steps()&&(target<=current||validate(current)))showStep(target)});loadCategoryTickets();showStep(0);
});
</script>
@endsection
